# Generated by Django 5.1.6 on 2025-02-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_city_region_courier_product_city_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='plain_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
