# Generated by Django 5.1.6 on 2025-02-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_product_latitude_product_longitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Shahar (tuman)', 'verbose_name_plural': 'Shaharlar (tumanlar)'},
        ),
        migrations.AlterModelOptions(
            name='courier',
            options={'verbose_name': 'Kuryer', 'verbose_name_plural': 'Kuryerlar'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Viloyat (shahar)', 'verbose_name_plural': 'Viloyatlar (shaharlar)'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Courier Boss', 'Operator')], max_length=255),
        ),
    ]
